apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-init-db
stringData:
  cb-init.sql: |
    CREATE ROLE dc WITH LOGIN PASSWORD '{{ .Values.dbPasswords.dc }}';
    CREATE ROLE qm WITH LOGIN PASSWORD '{{ .Values.dbPasswords.qm }}';

    CREATE SCHEMA IF NOT EXISTS dc;
    CREATE SCHEMA IF NOT EXISTS qm;

    GRANT ALL ON SCHEMA dc TO dc;
    GRANT ALL ON SCHEMA qm TO qm;
