{{- if .Values.backend.internal_db }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-init-db
stringData:
  cb-init.sql: |
    CREATE SCHEMA IF NOT EXISTS dc;
    CREATE SCHEMA IF NOT EXISTS qm;
    CREATE SCHEMA IF NOT EXISTS tm;
{{ end }}