{{- if .Values.backend.internal_db }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-pass
type: Opaque  
stringData:
  postgres-pass: {{ .Values.backend.cloudbeaver_db_password }}
{{- end }}