{{- if not .Values.backend.cloudbeaver_db_password }}
  {{- fail "Error: backend.cloudbeaver_db_password is missing or empty" }}
{{- end }}

{{- if eq .Values.backend.cloudbeaver_db_password "StR0NgP2sSw0rD" }}
  {{- fail "Error: Default password 'StR0NgP2sSw0rD' is insecure! Please change it before deployment." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-pass
type: Opaque
stringData:
  postgres-pass: {{ .Values.backend.cloudbeaver_db_password }}