apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-pass
type: Opaque  
stringData:
  postgres-pass: {{ .Values.dbPasswords.postgres }}
  dc-pass: {{ .Values.dbPasswords.dc }}
  qm-pass: {{ .Values.dbPasswords.qm }}