{{- $chainCertPath := print ( .Values.secretCertPath ) "/cert.crt" }}
{{- $keyCertPath := print ( .Values.secretCertPath ) "/key.key" }}

{{- if or (not (.Files.Get $chainCertPath)) (not (.Files.Get $keyCertPath)) }}
  {{- fail (printf "Error: One or both TLS files (%s, %s) are missing or empty" $chainCertPath $keyCertPath) }}
{{- end }}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-secret-ssl
data:
  tls.crt: {{ .Files.Get $chainCertPath | b64enc }}
  tls.key: {{ .Files.Get $keyCertPath | b64enc }}