---
{{- if eq .Values.ingressController "haproxy" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  annotations:
    haproxy-ingress.github.io/ingress.class: "haproxy"
    {{- if eq "https" .Values.httpScheme }}
    haproxy-ingress.github.io/ssl-redirect: "true"
    {{- end }}
    haproxy-ingress.github.io/path-rewrite: "/"
    haproxy-ingress.github.io/cookie-persistence: "cb-node-id"
    haproxy-ingress.github.io/proxy-body-size: "500m"
spec:
{{- if eq "https" .Values.httpScheme }}
  tls:
    - hosts:
      - {{ .Values.dbeaverTEBaseDomain }}
      secretName: {{ .Release.Name }}-ingress-tls
{{- end }}
  rules:
  - host: "{{ .Values.dbeaverTEBaseDomain }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dbeaver-te-web
              port:
                number: 8978
        - path: /dc
          pathType: Prefix
          backend:
            service:
              name: dbeaver-te-dc
              port:
                number: 8970
        - path: /rm
          pathType: Prefix
          backend:
            service:
              name: dbeaver-te-rm
              port:
                number: 8971
        - path: /qm
          pathType: Prefix
          backend:
            service:
              name: dbeaver-te-qm
              port:
                number: 8972
        - path: /tm
          pathType: Prefix
          backend:
            service:
              name: dbeaver-te-qm
              port:
                number: 8973                
{{ end }}