---
{{- if eq .Values.ingressController "aws-alb" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    {{- if eq "https" .Values.httpScheme }}
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificateARN }}"
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- end }}
    alb.ingress.kubernetes.io/rewrite-target: "/$1$2"
    alb.ingress.kubernetes.io/proxy-body-size: "500m"
    alb.ingress.kubernetes.io/load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=345600,idle_timeout.timeout_seconds=3600
spec:
  ingressClassName: alb
  rules:
  - host: "{{ .Values.cloudbeaverBaseDomain }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cloudbeaver-te
              port:
                number: 8978
        - path: /dc/
          pathType: Prefix
          backend:
            service:
              name: cloudbeaver-dc
              port:
                number: 8970
        - path: /rm/
          pathType: Prefix
          backend:
            service:
              name: cloudbeaver-rm
              port:
                number: 8971
        - path: /qm/
          pathType: Prefix
          backend:
            service:
              name: cloudbeaver-qm
              port:
                number: 8972
        - path: /tm/
          pathType: Prefix
          backend:
            service:
              name: cloudbeaver-tm
              port:
                number: 8973        
{{ end }}