---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-net
spec:
  policyTypes:
    - Ingress
  ingress:
    - {}
  podSelector:
    matchLabels:
      {{ .Release.Name }}-net: "true"
{{- if .Values.backend.internal_db }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-private-net
spec:
  podSelector:
    matchLabels:
      {{ .Release.Name }}-private-net: "true"
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ .Release.Name }}-private-net: "true"
      ports:
        - protocol: TCP
          port: 5432
{{ end }}