apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-net
spec:
  policyTypes:
    - Ingress
  ingress:
    - {}
  podSelector:
    matchLabels:
      {{ .Release.Name }}-net: "true"
