{{- with .Values.serviceAccount }}
{{- if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default "cloudbeaver" | quote }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
