CREATE ROLE dc WITH LOGIN PASSWORD 'dc';
CREATE ROLE qm WITH LOGIN PASSWORD 'qm';
CREATE ROLE rm WITH LOGIN PASSWORD 'rm';

CREATE SCHEMA IF NOT EXISTS dc;
CREATE SCHEMA IF NOT EXISTS qm;
CREATE SCHEMA IF NOT EXISTS rm;

GRANT ALL ON SCHEMA dc TO dc;
GRANT ALL ON SCHEMA qm TO qm;
GRANT ALL ON SCHEMA rm TO rm;