apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudbeaver-dc
  name: cloudbeaver-dc
spec:
  replicas: {{ .Values.cloudbeaverDC.replicaCount }}
  selector:
    matchLabels:
      app: cloudbeaver-dc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        date: "{{ now | unixEpoch }}"
        {{ .Release.Name }}-net: "true"
        app: cloudbeaver-dc
    spec:
      # securityContext:
      #     runAsUser: 1000
      #     runAsGroup: 1000
      #     fsGroup: 1000
      #     fsGroupChangePolicy: "Always"       
      containers:
        - image: "{{ .Values.cloudbeaverDC.image }}:{{ .Values.cloudbeaver.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.cloudbeaver.pullPolicy }}"
          env:
            - name: CLOUDBEAVER_DC_BACKEND_DB_URL
              value: jdbc:postgresql://postgres:5432/cloudbeaver?currentSchema=dc
            - name: CLOUDBEAVER_QM_BACKEND_DB_URL
              value: jdbc:postgresql://postgres:5432/cloudbeaver?currentSchema=qm
            - name: CLOUDBEAVER_DC_BACKEND_DB_USER
              value: dc
            - name: CLOUDBEAVER_DC_BACKEND_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-pass
                  key: dc-pass
            - name: CLOUDBEAVER_QM_BACKEND_DB_USER
              value: qm
            - name: CLOUDBEAVER_QM_BACKEND_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-pass
                  key: qm-pass
            - name: CLOUDBEAVER_DC_SERVER_URL
              value: "http://cloudbeaver-dc:8970/dc"
            - name: CLOUDBEAVER_RM_SERVER_URL
              value: "http://cloudbeaver-rm:8971/rm"
            - name: CLOUDBEAVER_QM_SERVER_URL
              value: "http://cloudbeaver-qm:8972/qm"
            - name: CLOUDBEAVER_PUBLIC_URL
              value: "{{ .Values.httpScheme }}://{{ .Values.cloudbeaverBaseDomain }}"
          name: cloudbeaver-dc
          ports:
            - containerPort: 8970
          resources: {}
          volumeMounts:
            - name: {{ .Release.Name }}-dc-data
              mountPath: /opt/domain-controller/workspace
            - name: private-cers
              mountPath: /opt/domain-controller/conf/certificates
              readOnly: true           
      {{- if .Values.cloudbeaver.pullCredsName }}
      imagePullSecrets:
        - name: {{ .Values.cloudbeaver.pullCredsName }}
      {{- end }}
      hostname: cloudbeaver-dc
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-dc-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dc-data
        - name: private-cers
          projected:
            sources:
              - secret:
                  name: {{ .Release.Name }}-crossservice-ssl
                  items:
                    - key: tls.key
                      path: dc-key.key
              - secret:
                  name: {{ .Release.Name }}-secret-ssl
                  items:
                    - key: tls.crt
                      path: secret-cert.crt
                    - key: tls.key
                      path: secret-key.key           