apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbeaver-te-qm
  name: dbeaver-te-qm
spec:
  replicas: {{ .Values.dbeaver_te_qm.replicaCount }}
  selector:
    matchLabels:
      app: dbeaver-te-qm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        date: "{{ now | unixEpoch }}"
        {{ .Release.Name }}-net: "true"
        {{ .Release.Name }}-private-net: "true"
        app: dbeaver-te-qm
    spec:
      # securityContext:
      #     runAsUser: 1000
      #     runAsGroup: 1000
      #     fsGroup: 1000
      #     fsGroupChangePolicy: "Always"
      containers:
        - image: "{{ .Values.dbeaver_te_qm.image }}:{{ .Values.dbeaverTE.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.dbeaverTE.pullPolicy }}"
          name: dbeaver-te-qm
          env:
            - name: DBEAVER_TE_DC_SERVER_URL
              value: "http://dbeaver-te-dc:8970/dc"
          ports:
            - containerPort: 8972
          resources: {}
          volumeMounts:
            - name: cross-ssl-cert
              mountPath: /opt/query-manager/conf/certificates
              readOnly: true
      {{- if .Values.dbeaverTE.pullCredsName }}
      imagePullSecrets:
        - name: {{ .Values.dbeaverTE.pullCredsName }}
      {{- end }}
      hostname: dbeaver-te-qm
      restartPolicy: Always
      volumes:
        - name: cross-ssl-cert
          secret:
            secretName: {{ .Release.Name }}-crossservice-ssl
            items:
              - key: tls.crt
                path: dc-cert.crt