apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbeaver-te-dc
  name: dbeaver-te-dc
spec:
  replicas: {{ .Values.dbeaver_te_dc.replicaCount }}
  selector:
    matchLabels:
      app: dbeaver-te-dc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        date: "{{ now | unixEpoch }}"
        {{ .Release.Name }}-net: "true"
        {{ .Release.Name }}-private-net: "true"
        app: dbeaver-te-dc
    spec:
      # securityContext:
      #     runAsUser: 1000
      #     runAsGroup: 1000
      #     fsGroup: 1000
      #     fsGroupChangePolicy: "Always"
      containers:
        - image: "{{ .Values.dbeaver_te_dc.image }}:{{ .Values.dbeaverTE.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.dbeaverTE.pullPolicy }}"
          name: dbeaver-te-dc
          env:
            - name: DBEAVER_TE_DC_BACKEND_DB_URL
              value: "{{ .Values.backend.dbeaver_te_db_url }}?currentSchema=dc"
            - name: DBEAVER_TE_DC_BACKEND_DB_USER
              value: "{{ .Values.backend.dbeaver_te_db_user }}"
            - name: DBEAVER_TE_DC_BACKEND_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-pass
                  key: postgres-pass
            - name: DBEAVER_TE_QM_BACKEND_DB_URL
              value: "{{ .Values.backend.dbeaver_te_db_url }}?currentSchema=qm"
            - name: DBEAVER_TE_QM_BACKEND_DB_USER
              value: "{{ .Values.backend.dbeaver_te_db_user }}"
            - name: DBEAVER_TE_QM_BACKEND_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-pass
                  key: postgres-pass
            - name: DBEAVER_TE_TM_BACKEND_DB_URL
              value: "{{ .Values.backend.dbeaver_te_db_url }}?currentSchema=tm"
            - name: DBEAVER_TE_TM_BACKEND_DB_USER
              value: "{{ .Values.backend.dbeaver_te_db_user }}"
            - name: DBEAVER_TE_TM_BACKEND_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-pass
                  key: postgres-pass
            - name: DBEAVER_TE_DC_SERVER_URL
              value: "http://dbeaver-te-dc:8970/dc"
            - name: DBEAVER_TE_RM_SERVER_URL
              value: "http://dbeaver-te-rm:8971/rm"
            - name: DBEAVER_TE_QM_SERVER_URL
              value: "http://dbeaver-te-qm:8972/qm"
            - name: DBEAVER_TE_PUBLIC_URL
              value: "{{ .Values.httpScheme }}://{{ .Values.dbeaverTEBaseDomain }}"
          ports:
            - containerPort: 8970
          resources: {}
          volumeMounts:
            - name: {{ .Release.Name }}-dc-data
              mountPath: /opt/domain-controller/workspace
            - name: private-cers
              mountPath: /opt/domain-controller/conf/certificates
              readOnly: true
      {{- if .Values.dbeaverTE.pullCredsName }}
      imagePullSecrets:
        - name: {{ .Values.dbeaverTE.pullCredsName }}
      {{- end }}
      hostname: dbeaver-te-dc
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-dc-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dc-data
        - name: private-cers
          projected:
            sources:
              - secret:
                  name: {{ .Release.Name }}-crossservice-ssl
                  items:
                    - key: tls.key
                      path: dc-key.key
              - secret:
                  name: {{ .Release.Name }}-secret-ssl
                  items:
                    - key: tls.crt
                      path: secret-cert.crt
                    - key: tls.key
                      path: secret-key.key