CREATE ROLE dc WITH LOGIN PASSWORD 'DCpassword';
CREATE ROLE qm WITH LOGIN PASSWORD 'QMpassword';

CREATE SCHEMA IF NOT EXISTS dc;
CREATE SCHEMA IF NOT EXISTS qm;

GRANT ALL ON SCHEMA dc TO dc;
GRANT ALL ON SCHEMA qm TO qm;
