# run as root before up this compose:
#   loginctl enable-linger 1000
#   echo 'net.ipv4.ip_unprivileged_port_start=80' >> /etc/sysctl.conf
#   sysctl -p

version: '3'
volumes:
  metadata_data: {}
  dc_data: {}
  rm_data: {}
  tm_data: {}
  nginx_ssl_data: {}
  nginx_conf_data: {}
  trusted_cacerts: {}
  api_tokens: {}
networks:
  cloudbeaver-te-private-net: null
services:
  web-proxy:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-${PROXY_TYPE:-nginx}:${CLOUDBEAVER_VERSION_TAG}
    ports:
      - 80:8080
      - 443:8443
    environment:
      - PRODUCT_TYPE=te
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-dbeaver}
      - CLOUDBEAVER_WEB_SERVER_PORT=${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    networks:
      - cloudbeaver-te-private-net
    volumes:
      - nginx_conf_data:/etc/${PROXY_TYPE:-nginx}/product-conf/:z
      - nginx_ssl_data:/etc/${PROXY_TYPE:-nginx}/ssl/:z
    depends_on:
      - cloudbeaver-te
      - cloudbeaver-dc
      - cloudbeaver-rm
      - cloudbeaver-qm
      - cloudbeaver-tm
  kafka:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-kafka:3.9
    hostname: kafka
    expose:
      - 9092
    networks:
      - cloudbeaver-te-private-net
  postgres:
    restart: unless-stopped
    hostname: postgres
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-postgres:14
    volumes:
      - metadata_data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    expose:
      - 5432
    networks:
      - cloudbeaver-te-private-net
  cloudbeaver-dc:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-dc:${CLOUDBEAVER_VERSION_TAG}
    hostname: cloudbeaver-dc
    environment:
      - CLOUDBEAVER_PUBLIC_URL=${CLOUDBEAVER_PUBLIC_URL}      
      - CLOUDBEAVER_DC_SERVER_URL=http://cloudbeaver-dc:8970/dc
      - CLOUDBEAVER_RM_SERVER_URL=http://cloudbeaver-rm:8971/rm
      - CLOUDBEAVER_QM_SERVER_URL=http://cloudbeaver-qm:8972/qm
      - CLOUDBEAVER_TM_SERVER_URL=http://cloudbeaver-tm:8973/tm
      - CLOUDBEAVER_DC_BACKEND_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DC_BACKEND_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DC_BACKEND_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_QM_BACKEND_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_QM_BACKEND_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_QM_BACKEND_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_TM_BACKEND_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_TM_BACKEND_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_TM_BACKEND_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_QM_BACKEND_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DC_BACKEND_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_TM_BACKEND_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
    volumes:
      - dc_data:/opt/domain-controller/workspace:z
      - ./cert/private/:/opt/domain-controller/conf/certificates/:z
      - ./cert/public/:/opt/domain-controller/conf/certificates/public/:z
      - trusted_cacerts:/opt/domain-controller/conf/certificates/custom/:z      
      - api_tokens:/opt/domain-controller/conf/keys/:z
    expose:
      - 8970
    networks:
      - cloudbeaver-te-private-net
  cloudbeaver-te:
    restart: unless-stopped
    hostname: cloudbeaver-te
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-te:${CLOUDBEAVER_VERSION_TAG}
    deploy:
      replicas: ${REPLICA_COUNT_TE:-1}
    volumes:
      - ./cert/public/:/opt/cloudbeaver/conf/certificates/:z
      - trusted_cacerts:/opt/cloudbeaver/conf/certificates/custom/:z
    environment:
      - CLOUDBEAVER_DC_SERVER_URL=http://cloudbeaver-dc:8970/dc
    expose:
      - ${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    depends_on:
      - cloudbeaver-dc
      - cloudbeaver-rm
      - cloudbeaver-qm
    networks:
      - cloudbeaver-te-private-net
  cloudbeaver-rm:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-rm:${CLOUDBEAVER_VERSION_TAG}
    hostname: cloudbeaver-rm
    deploy:
      replicas: ${REPLICA_COUNT_RM:-1}
    environment:
      - CLOUDBEAVER_DC_SERVER_URL=http://cloudbeaver-dc:8970/dc
    volumes:
      - rm_data:/opt/resource-manager/workspace:z
      - ./cert/public/:/opt/resource-manager/conf/certificates/:z
      - trusted_cacerts:/opt/resource-manager/conf/certificates/custom/:z      
    depends_on:
      - cloudbeaver-dc
    expose:
      - 8971
    networks:
      - cloudbeaver-te-private-net
  cloudbeaver-qm:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-qm:${CLOUDBEAVER_VERSION_TAG}
    hostname: cloudbeaver-qm
    deploy:
      replicas: ${REPLICA_COUNT_QM:-1}
    environment:
      - CLOUDBEAVER_DC_SERVER_URL=http://cloudbeaver-dc:8970/dc
    volumes:
      - ./cert/public/:/opt/query-manager/conf/certificates/:z
      - trusted_cacerts:/opt/query-manager/conf/certificates/custom/:z
    depends_on:
      - cloudbeaver-dc
    expose:
      - 8972
    networks:
      - cloudbeaver-te-private-net
  cloudbeaver-tm:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-tm:${CLOUDBEAVER_VERSION_TAG}
    hostname: cloudbeaver-tm
    deploy:
      replicas: ${REPLICA_COUNT_TM:-1}
    environment:
      - CLOUDBEAVER_DC_SERVER_URL=http://cloudbeaver-dc:8970/dc
    volumes:
      - tm_data:/opt/task-manager/workspace:z
      - ./cert/public/:/opt/task-manager/conf/certificates/:z
      - trusted_cacerts:/opt/task-manager/conf/certificates/custom/:z
    depends_on:
      - cloudbeaver-dc
    expose:
      - 8973
    networks:
      - cloudbeaver-te-private-net
