name: "Commit Message Validation"

on:
  pull_request:
    branches:
      - devel
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - labeled

jobs:
  commit-msg-matcher:
    runs-on: ubuntu-latest
    steps:     
      - name: Use local commit-msg-matcher
        uses: dbeaver/github-actions/commit-msg-matcher@devel
        with:
          githubAccessToken: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}
          jiraAccessToken: ${{ secrets.JIRA_DEVOPS_TICKET_RO_TOKEN }}
